# Travis CI Configuration File

<<<<<<< HEAD
# Tell Travis CI we're using PHP
language: php
=======
# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# Commands you want to run that will verify your build.
script: phpunit
>>>>>>> 44d53ed8b45f5a114a71d89b890f72cf062c484d

# Build matrix options
matrix:
  include:
    - php: 5.5
      env: WP_TRAVISCI=travis:js
    - php: 5.2
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.3
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.4
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.5
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.6
      env: WP_TRAVISCI=travis:phpunit
    - php: hhvm
      env: WP_TRAVISCI=travis:phpunit
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true


# Script, failures in this section will result in build status 'failed'
script: "phpunit -c tests/phpunit.xml.dist"